app:
  port: 3000

session:
  cookie:
    secret: averylogphrasebiggerthanthirtytwochars #get env vars?
    max-age: 86400000 #24h in milliseconds

db:
  host: localhost
  port: 3306
  name: nataha
  username: user
  password: user
